Traceback (most recent call last):
  File "/Users/janc/miniconda/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/janc/miniconda/lib/python3.7/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/janc/miniconda/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/janc/miniconda/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/janc/miniconda/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Users/janc/miniconda/lib/python3.7/site-packages/nbclient/client.py", line 536, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/janc/miniconda/lib/python3.7/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/janc/miniconda/lib/python3.7/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import sklearn
import matplotlib.pyplot as plt
import librosa.feature
from matplotlib.colors import ListedColormap, LinearSegmentedColormap
import colorcet as cc
import matplotlib
import deepss_unsupervised.spec_utils
import umap
import hdbscan
from io import BytesIO
import urllib.request

plt.style.use('ncb.mplstyle')
------------------

[0;31m-------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                       Traceback (most recent call last)
[0;32m~/miniconda/lib/python3.7/site-packages/matplotlib/style/core.py[0m in [0;36muse[0;34m(style)[0m
[1;32m    120[0m             [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 121[0;31m                 [0mrc[0m [0;34m=[0m [0mrc_params_from_file[0m[0;34m([0m[0mstyle[0m[0;34m,[0m [0muse_default_template[0m[0;34m=[0m[0;32mFalse[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    122[0m                 [0m_apply_style[0m[0;34m([0m[0mrc[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/miniconda/lib/python3.7/site-packages/matplotlib/__init__.py[0m in [0;36mrc_params_from_file[0;34m(fname, fail_on_error, use_default_template)[0m
[1;32m    873[0m     """
[0;32m--> 874[0;31m     [0mconfig_from_file[0m [0;34m=[0m [0m_rc_params_in_file[0m[0;34m([0m[0mfname[0m[0;34m,[0m [0mfail_on_error[0m[0;34m=[0m[0mfail_on_error[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    875[0m [0;34m[0m[0m

[0;32m~/miniconda/lib/python3.7/site-packages/matplotlib/__init__.py[0m in [0;36m_rc_params_in_file[0;34m(fname, transform, fail_on_error)[0m
[1;32m    802[0m     [0mrc_temp[0m [0;34m=[0m [0;34m{[0m[0;34m}[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 803[0;31m     [0;32mwith[0m [0m_open_file_or_url[0m[0;34m([0m[0mfname[0m[0;34m)[0m [0;32mas[0m [0mfd[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    804[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/miniconda/lib/python3.7/contextlib.py[0m in [0;36m__enter__[0;34m(self)[0m
[1;32m    111[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 112[0;31m             [0;32mreturn[0m [0mnext[0m[0;34m([0m[0mself[0m[0;34m.[0m[0mgen[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    113[0m         [0;32mexcept[0m [0mStopIteration[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/miniconda/lib/python3.7/site-packages/matplotlib/__init__.py[0m in [0;36m_open_file_or_url[0;34m(fname)[0m
[1;32m    780[0m             [0mencoding[0m [0;34m=[0m [0;34m"utf-8"[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 781[0;31m         [0;32mwith[0m [0mopen[0m[0;34m([0m[0mfname[0m[0;34m,[0m [0mencoding[0m[0;34m=[0m[0mencoding[0m[0;34m)[0m [0;32mas[0m [0mf[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    782[0m             [0;32myield[0m [0mf[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'ncb.mplstyle'

The above exception was the direct cause of the following exception:

[0;31mOSError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-1-8f1e24ca7d51>[0m in [0;36m<module>[0;34m[0m
[1;32m     12[0m [0;32mimport[0m [0murllib[0m[0;34m.[0m[0mrequest[0m[0;34m[0m[0;34m[0m[0m
[1;32m     13[0m [0;34m[0m[0m
[0;32m---> 14[0;31m [0mplt[0m[0;34m.[0m[0mstyle[0m[0;34m.[0m[0muse[0m[0;34m([0m[0;34m'ncb.mplstyle'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/miniconda/lib/python3.7/site-packages/matplotlib/style/core.py[0m in [0;36muse[0;34m(style)[0m
[1;32m    125[0m                     [0;34m"{!r} not found in the style library and input is not a "[0m[0;34m[0m[0;34m[0m[0m
[1;32m    126[0m                     [0;34m"valid URL or path; see `style.available` for list of "[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 127[0;31m                     "available styles".format(style)) from err
[0m[1;32m    128[0m [0;34m[0m[0m
[1;32m    129[0m [0;34m[0m[0m

[0;31mOSError[0m: 'ncb.mplstyle' not found in the style library and input is not a valid URL or path; see `style.available` for list of available styles
OSError: 'ncb.mplstyle' not found in the style library and input is not a valid URL or path; see `style.available` for list of available styles

